application: rss2hipchat
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /tasks/.*
  script: tasks.app
  login: admin
  secure: always

- url: .*
  script: main.app
  login: admin
  secure: always

libraries:
- name: webapp2
  version: "2.5.1"
